services:
    gunicorn:
        build: .
        command: "gunicorn main:app --bind 0.0.0.0:8000"
        ports:
          - "8000:8000"
    nginx:
        image: nginx
        ports:
          - "8080:8080"
        volumes:
          - ./nginx.conf:/etc/nginx/nginx.conf
          - ./public/:/public/
        depends_on:
            - gunicorn
